/**
 * pos-lib.mjs —— 词性推断共享库（fix-pos.mjs 与 build-wordbook.mjs 共用）
 *
 * 处理对象：释义无词性前缀、pos 为空的词条。
 * 四层策略（按优先级）：
 *  1. 尾部词性标记提取："预先确定，注定 (vt.)" → vt.
 *  2. 手动映射表：考试常用词，最准确（harbour → n.；vt.）
 *  3. 后缀规则：复合词 / -tion / -ize / -ous 等
 *  4. 交叉回填：其他词库中同词已有词性（由 fix-pos.mjs 负责）
 */

/** 常用词手动映射：word(lower) -> 词性数组（顺序对应释义分段 m） */
export const POS_OVERRIDES = {
  // ---- cet4 / kaoyan / ielts 常见缺词性词 ----
  harbour: ['n.', 'vt.'],
  harbor: ['n.', 'vt.'],
  preposition: ['prep.'],
  christ: ['n.'],
  draught: ['n.', 'adj.'],
  pint: ['n.'],
  aeroplane: ['n.'],
  lavatory: ['n.'],
  volt: ['n.'],
  humour: ['n.'],
  humor: ['n.'],
  supreme: ['adj.'],
  means: ['n.', 'v.'],
  fibre: ['n.'],
  fiber: ['n.'],
  honourable: ['adj.'],
  honorable: ['adj.'],
  petrol: ['n.'],
  vapour: ['n.'],
  vapor: ['n.'],
  favourite: ['adj.', 'n.'],
  favorite: ['adj.', 'n.'],
  aluminium: ['n.'],
  aluminum: ['n.'],
  millimetre: ['n.'],
  millimeter: ['n.'],
  waken: ['v.'],
  dictation: ['n.'],
  congratulation: ['n.'],
  fortnight: ['n.'],
  systematical: ['adj.'],
  fourfold: ['adv.', 'adj.'],
  criminology: ['n.'],
  gramme: ['n.'],
  'world-wide': ['adj.'],
  rumour: ['n.'],
  rumor: ['n.'],
  favour: ['n.', 'v.'],
  favor: ['n.', 'v.'],
  acre: ['n.'],
  centimetre: ['n.'],
  centimeter: ['n.'],
  gram: ['n.'],
  typist: ['n.'],
  connexion: ['n.'],
  connection: ['n.'],
  civilize: ['vt.'],
  civilise: ['vt.'],
  remonstrate: ['vi.'],
  gaol: ['n.', 'vt.'],
  jail: ['n.', 'vt.'],
  neighbourhood: ['n.'],
  neighborhood: ['n.'],
  enquiry: ['n.'],
  inquire: ['v.'],
  enquire: ['v.'],
  consultancy: ['n.'],
  industrialize: ['vt.'],
  industrialise: ['vt.'],
  congress: ['n.'],
  pants: ['n.'],
  astrophysics: ['n.'],
  favourable: ['adj.'],
  favorable: ['adj.'],
  mould: ['n.', 'v.'],
  mold: ['n.', 'v.'],
  gallon: ['n.'],
  accountancy: ['n.'],
  punctual: ['adj.'],
  centigrade: ['adj.', 'n.'],
  tyre: ['n.'],
  tire: ['n.', 'v.'],
  lorry: ['n.'],
  ounce: ['n.'],
  // ---- cet6 ----
  predestine: ['vt.'],
  watt: ['n.'],
  distill: ['vt.'],
  lubricate: ['vt.'],
  watertight: ['adj.'],
  glamor: ['n.'],
  glamour: ['n.'],
  corrode: ['v.'],
  calorie: ['n.'],
  isle: ['n.'],
  criterion: ['n.'],
  ventilate: ['vt.'],
  saleable: ['adj.'],
  overpass: ['n.'],
  minibus: ['n.'],
  nil: ['n.'],
  situated: ['adj.'],
  practicable: ['adj.'],
  esthetic: ['adj.'],
  aesthetic: ['adj.'],
  bewilder: ['vt.'],
  proceeding: ['n.'],
  deferential: ['adj.'],
  destined: ['adj.'],
  quart: ['n.'],
  // ---- kaoyan ----
  fantastical: ['adj.'],
  litre: ['n.'],
  liter: ['n.'],
  gasolene: ['n.'],
  gasoline: ['n.'],
  fertiliser: ['n.'],
  fertilizer: ['n.'],
  marvellous: ['adj.'],
  marvelous: ['adj.'],
  paralyse: ['vt.'],
  paralyze: ['vt.'],
  'by-pass': ['n.'],
  snobbish: ['adj.'],
  decimal: ['adj.', 'n.'],
  'vs.': ['prep.'],
  characterise: ['vt.'],
  characterize: ['vt.'],
  despatch: ['v.', 'n.'],
  dispatch: ['v.', 'n.'],
  tropic: ['n.', 'adj.'],
  gage: ['n.'],
  licence: ['n.', 'vt.'],
  license: ['n.', 'vt.'],
  'a.': ['n.'],
  waggon: ['n.'],
  wagon: ['n.'],
  fatigued: ['adj.'],
  tumour: ['n.'],
  tumor: ['n.'],
  roundabout: ['adj.', 'n.'],
  badminton: ['n.'],
  organise: ['vt.'],
  organize: ['vt.'],
  daunt: ['vt.'],
  shilling: ['n.'],
  blog: ['n.'],
  emphasise: ['vt.'],
  emphasize: ['vt.'],
  cosy: ['adj.'],
  cozy: ['adj.'],
  encyclopaedia: ['n.'],
  encyclopedia: ['n.'],
  jewellery: ['n.'],
  jewelry: ['n.'],
  civilisation: ['n.'],
  civilization: ['n.'],
  dynamical: ['adj.'],
  odour: ['n.'],
  odor: ['n.'],
  credentials: ['n.'],
  appall: ['vt.'],
  appal: ['vt.'],
  sympathise: ['vi.'],
  sympathize: ['vi.'],
  generalise: ['v.'],
  generalize: ['v.'],
  specialise: ['vi.'],
  specialize: ['vi.'],
  tactics: ['n.'],
  speciality: ['n.'],
  mutton: ['n.'],
  sulphur: ['n.'],
  sulfur: ['n.'],
  typhoon: ['n.'],
  archeology: ['n.'],
  archaeology: ['n.'],
  invariable: ['adj.'],
  instalment: ['n.'],
  installment: ['n.'],
  analogue: ['n.'],
  statical: ['adj.'],
  static: ['adj.', 'n.'],
  april: ['n.'],
  organisation: ['n.'],
  organization: ['n.'],
  mobilise: ['vt.'],
  mobilize: ['vt.'],
  trolly: ['n.'],
  trolley: ['n.'],
  recognise: ['vt.'],
  recognize: ['vt.'],
  bacterium: ['n.'],
  passerby: ['n.'],
  highjack: ['vt.'],
  hijack: ['vt.'],
  botany: ['n.'],
  reflexion: ['n.'],
  reflection: ['n.'],
  // ---- ielts ----
  ecliptic: ['n.', 'adj.'],
  overrate: ['vt.'],
  authenticate: ['vt.'],
  decapitate: ['vt.'],
  inflammable: ['adj.'],
  incinerate: ['vt.'],
  reorient: ['vt.'],
  orientate: ['vt.'],
  infirmity: ['n.'],
  curative: ['adj.', 'n.'],
  microbiology: ['n.'],
  'in comparison with': ['prep.'],
  cameral: ['adj.'],
  wastage: ['n.'],
  impoverish: ['vt.'],
  calibre: ['n.'],
  caliber: ['n.'],
  herbivore: ['n.'],
  'vice versa': ['adv.'],
  subsoil: ['n.'],
  'fact sheet': ['n.'],
  opulence: ['n.'],
  dystrophy: ['n.'],
  stabilise: ['v.'],
  stabilize: ['v.'],
  stereoscopic: ['adj.'],
  familiarise: ['vt.'],
  familiarize: ['vt.'],
  arboreal: ['adj.'],
  refundable: ['adj.'],
  teem: ['vi.'],
  optometrist: ['n.'],
  marsupial: ['n.', 'adj.'],
  enfranchise: ['vt.'],
  disempower: ['vt.'],
  unprejudiced: ['adj.'],
  wretch: ['n.'],
  pumice: ['n.', 'vt.'],
  cinematography: ['n.'],
  storyline: ['n.'],
  keystone: ['n.'],
  pulverise: ['vt.'],
  pulverize: ['vt.'],
  savour: ['v.', 'n.'],
  savor: ['v.', 'n.'],
  revegetate: ['vi.'],
  commiserate: ['vi.'],
  mime: ['v.', 'n.'],
  underling: ['n.'],
  extendable: ['adj.'],
  'kung fu': ['n.'],
  'colour-blind': ['adj.'],
  'color-blind': ['adj.'],
  consignment: ['n.'],
  fertilise: ['vt.'],
  fertilize: ['vt.'],
  deviance: ['n.'],
  retrenchment: ['n.'],
  repatriate: ['vt.'],
  truant: ['v.', 'n.'],
  guzzle: ['v.'],
  spoilage: ['n.'],
  sophisticate: ['n.'],
  acclimatise: ['v.'],
  acclimatize: ['v.'],
  abode: ['n.'],
  conductive: ['adj.'],
  synchronise: ['v.'],
  synchronize: ['v.'],
  mandarin: ['n.'],
  intermix: ['v.'],
  'in addition to': ['prep.'],
  capsize: ['v.'],
  overwork: ['v.', 'n.'],
  emboss: ['vt.'],
  goggles: ['n.'],
  inferential: ['adj.'],
  requisition: ['n.', 'vt.'],
  'tick off': ['vt.'],
  astrology: ['n.'],
  perquisite: ['n.'],
  tillable: ['adj.'],
  counsellor: ['n.'],
  counselor: ['n.'],
  utilise: ['vt.'],
  utilize: ['vt.'],
  propellant: ['n.'],
  'for instance': ['adv.'],
  flavour: ['n.', 'vt.'],
  flavor: ['n.', 'vt.'],
  epitomise: ['vt.'],
  epitomize: ['vt.'],
  subtropical: ['adj.'],
  ejection: ['n.'],
  exploitative: ['adj.'],
  disharmony: ['n.'],
  unquote: ['vi.'],
  freefone: ['n.'],
  slacken: ['v.'],
  memorise: ['vt.'],
  memorize: ['vt.'],
  luxuriant: ['adj.'],
  slurry: ['n.'],
  liaise: ['vi.'],
  landward: ['adj.', 'adv.'],
  zoological: ['adj.'],
  storey: ['n.'],
  story: ['n.'],
  mastercard: ['n.'],
  pronounceable: ['adj.'],
  introvert: ['n.'],
  thrifty: ['adj.'],
  unbeatable: ['adj.'],
  inductive: ['adj.'],
  megacity: ['n.'],
  pliable: ['adj.'],
  indolent: ['adj.'],
  disorientate: ['vt.'],
  tropospheric: ['adj.'],
  navigable: ['adj.'],
  refresher: ['n.'],
  afflicting: ['adj.'],
  arable: ['adj.', 'n.'],
  melatonin: ['n.'],
  merchandising: ['n.'],
  moribund: ['adj.'],
  consequential: ['adj.'],
  minimise: ['vt.'],
  minimize: ['vt.'],
  bronchitis: ['n.'],
  'for the sake of': ['prep.'],
  absenteeism: ['n.'],
  sluttish: ['adj.'],
  postgraduate: ['n.'],
  scorching: ['adj.'],
  decompression: ['n.'],
  'water-borne': ['adj.'],
  unblemished: ['adj.'],
  plough: ['n.', 'v.'],
  plow: ['n.', 'v.'],
  magma: ['n.'],
  inhumane: ['adj.'],
  trapeze: ['n.'],
  recreate: ['vt.'],
  burgeon: ['vi.'],
  apace: ['adv.'],
  criticise: ['v.'],
  criticize: ['v.'],
  collate: ['vt.'],
  excreta: ['n.'],
  computerize: ['vt.'],
  tensile: ['adj.'],
  leukaemia: ['n.'],
  leukemia: ['n.'],
  'at least': ['adv.'],
  'solar-powered': ['adj.'],
  splint: ['n.', 'vt.'],
  assistantship: ['n.'],
  unconquerable: ['adj.'],
  bookrest: ['n.'],
  sledge: ['n.', 'v.'],
  cookery: ['n.'],
  transmute: ['vt.'],
  'check-up': ['n.'],
  expiry: ['n.'],
  compulsively: ['adv.'],
  cavort: ['vi.'],
  unregistered: ['adj.'],
  undisguised: ['adj.'],
  slander: ['v.', 'n.'],
  'in addition': ['adv.'],
  ulterior: ['adj.'],
  workaholic: ['n.'],
  discourteous: ['adj.'],
  aridity: ['n.'],
  starchy: ['adj.'],
  glutamate: ['n.'],
  cloakroom: ['n.'],
  defence: ['n.'],
  defense: ['n.'],
  prefabricate: ['vt.'],
  slothful: ['adj.'],
  objectify: ['vt.'],
  homestay: ['n.'],
  excusable: ['adj.'],
  onwards: ['adv.'],
  chink: ['v.', 'n.'],
  sociable: ['adj.'],
  siesta: ['n.'],
  dispiriting: ['adj.'],
  authorise: ['vt.'],
  authorize: ['vt.'],
  pollinate: ['vt.'],
  enrolment: ['n.'],
  enrollment: ['n.'],
  artefact: ['n.'],
  artifact: ['n.'],
  decibel: ['n.'],
  conduce: ['vi.'],
  scrupulous: ['adj.'],
  procrastinate: ['vi.'],
  subsidise: ['vt.'],
  subsidize: ['vt.'],
  aeration: ['n.'],
  remuneration: ['n.'],
  inalienable: ['adj.'],
  summarise: ['v.'],
  summarize: ['v.'],
  'and so forth': ['adv.'],
  finitude: ['n.'],
  'notice board': ['n.'],
  internationalist: ['adj.', 'n.'],
  venomous: ['adj.'],
  extrusion: ['n.'],
  'inductive reasoning': ['n.'],
  sundial: ['n.'],
  seclude: ['vt.'],
  aggravation: ['n.'],
  imprecise: ['adj.'],
  disenchantment: ['n.'],
  crockery: ['n.'],
  bereave: ['vt.'],
  overdraft: ['n.'],
  viscous: ['adj.'],
  'eco-friendly': ['adj.'],
  extrovert: ['n.'],
  'in accordance with': ['prep.'],
  tenable: ['adj.'],
  ultraclean: ['adj.'],
  'bump into': ['vt.'],
  edify: ['vt.'],
  sceptical: ['adj.'],
  skeptical: ['adj.'],
  inborn: ['adj.'],
  tangibly: ['adv.'],
  holistically: ['adv.'],
  sinew: ['n.'],
  studious: ['adj.'],
  maltreat: ['vt.'],
  'at random': ['adv.'],
  meteorology: ['n.'],
  meagre: ['adj.'],
  meager: ['adj.'],
  'in favour of': ['prep.'],
  'in favor of': ['prep.'],
  'a calculated crime': ['n.'],
  cosset: ['vt.'],
  insularity: ['n.'],
  honour: ['n.', 'vt.'],
  honor: ['n.', 'vt.'],
  repack: ['vt.'],
  subliminal: ['adj.'],
  elicitation: ['n.'],
  lexicographer: ['n.'],
  herdsman: ['n.'],
  embezzlement: ['n.'],
  'roll film': ['n.'],
  begrimed: ['adj.'],
  alluvial: ['adj.', 'n.'],
  fumes: ['n.'],
  cantonese: ['n.', 'adj.'],
  incongruity: ['n.'],
  overfill: ['v.'],
  endeavour: ['n.', 'vi.'],
  endeavor: ['n.', 'vi.'],
  laterality: ['n.'],
  begrudge: ['vt.'],
  townscape: ['n.'],
  overgraze: ['v.'],
  exhaustible: ['adj.'],
  estrange: ['vt.'],
  maximise: ['vt.'],
  maximize: ['vt.'],
  unobtrusive: ['adj.'],
  outsell: ['vt.'],
  turbid: ['adj.'],
  coexist: ['vi.'],
  overexploit: ['vt.'],
  modish: ['adj.'],
  aeronautics: ['n.'],
  hectare: ['n.'],
  acrobatic: ['adj.'],
  niggle: ['v.'],
  foreland: ['n.'],
  postcode: ['n.'],
  resit: ['v.', 'n.'],
  overlie: ['vt.'],
  generative: ['adj.'],
  jeopardise: ['vt.'],
  jeopardize: ['vt.'],
  harridan: ['n.'],
  demerit: ['n.'],
  utilisation: ['n.'],
  utilization: ['n.'],
  'easy-going': ['adj.'],
  bin: ['n.'],
  unsanitary: ['adj.'],
  aggressiveness: ['n.'],
  signpost: ['n.', 'vt.'],
  abhorrent: ['adj.'],
  biometrics: ['n.'],
  irrevocable: ['adj.'],
  flexitime: ['n.'],
  breakwater: ['n.'],
  decouple: ['vt.'],
  helix: ['n.'],
  domesticate: ['vt.'],
  apportion: ['vt.'],
  refectory: ['n.'],
  inviolable: ['adj.'],
  dormancy: ['n.'],
  alchemist: ['n.'],
  enhancer: ['n.'],
  untrustworthy: ['adj.'],
  neoclassical: ['adj.'],
  regurgitate: ['v.'],
  despoil: ['vt.'],
  windscreen: ['n.'],
  graphology: ['n.'],
  manoeuvre: ['v.', 'n.'],
  maneuver: ['v.', 'n.'],
  socialise: ['v.'],
  socialize: ['v.'],
  gullibly: ['adv.'],
  plagiarise: ['v.'],
  plagiarize: ['v.'],
  victimise: ['vt.'],
  victimize: ['vt.'],
  'in vain': ['adv.'],
  spasmodic: ['adj.'],
  foetus: ['n.'],
  fetus: ['n.'],
  instinctual: ['adj.'],
  earthwork: ['n.'],
  earthworm: ['n.'],
  // ---- toefl ----
  twinkling: ['adj.', 'n.'],
  customs: ['n.'],
  corporeal: ['adj.'],
  legible: ['adj.'],
  ageism: ['n.'],
  syntactic: ['adj.'],
  capillary: ['adj.', 'n.'],
  deform: ['v.'],
  tectonic: ['adj.'],
  verifiable: ['adj.'],
  emancipate: ['vt.'],
  snide: ['adj.'],
  penmanship: ['n.'],
  flagellum: ['n.'],
  rhinoceros: ['n.'],
  odorous: ['adj.'],
  seismograph: ['n.'],
  hypertext: ['n.'],
  oceanographer: ['n.'],
  officious: ['adj.'],
  unaided: ['adj.'],
  pliant: ['adj.'],
  cohabitation: ['n.'],
  speckle: ['v.', 'n.'],
  foment: ['vt.'],
  antonym: ['n.'],
  homing: ['adj.'],
  crustacean: ['adj.', 'n.'],
  untamed: ['adj.'],
  suborn: ['vt.'],
  ordinal: ['adj.', 'n.'],
  telecommunication: ['n.'],
  cranial: ['adj.'],
  anomie: ['n.'],
  silicate: ['n.'],
  listless: ['adj.'],
  bilingualism: ['n.'],
  satiric: ['adj.'],
  encrust: ['vt.'],
  upsurge: ['n.'],
  depredation: ['n.'],
  certitude: ['n.'],
  cookout: ['n.'],
  inconspicuous: ['adj.'],
  unadorned: ['adj.'],
  meridian: ['n.'],
  dote: ['vi.'],
  sequoia: ['n.'],
  amenity: ['n.'],
  finch: ['n.'],
  photodissociation: ['n.'],
  imbibe: ['v.'],
  impermeable: ['adj.'],
  precautionary: ['adj.'],
  append: ['vt.'],
  copilot: ['n.'],
  bellows: ['n.'],
  patriarchic: ['adj.'],
  liquefy: ['v.'],
  digression: ['n.'],
  melanin: ['n.'],
  disinterest: ['n.'],
  disconcert: ['vt.'],
  overact: ['vi.'],
  oversleep: ['vi.'],
  oratorio: ['n.'],
  apportionment: ['n.'],
  tyrannical: ['adj.'],
  opal: ['n.'],
  rayon: ['n.'],
  scornful: ['adj.'],
  beneficent: ['adj.'],
  gilding: ['n.'],
  paleolithic: ['adj.', 'n.'],
  tangent: ['adj.', 'n.'],
  aberrant: ['adj.'],
  ellipse: ['n.'],
  muggy: ['adj.'],
  chaste: ['adj.'],
  confederacy: ['n.'],
  hominid: ['n.', 'adj.'],
  conductivity: ['n.'],
  associative: ['adj.'],
  backhand: ['n.'],
  cubism: ['n.'],
  abortive: ['adj.'],
  refraction: ['n.'],
  insolvent: ['adj.'],
  empiricism: ['n.'],
  annotation: ['n.'],
  mechanics: ['n.'],
  toed: ['adj.'],
  maglev: ['n.'],
  sled: ['v.', 'n.'],
  polygamous: ['adj.'],
  gemstone: ['n.'],
  gibe: ['v.', 'n.'],
  staggered: ['adj.'],
  transact: ['v.'],
  loathsome: ['adj.'],
  preeminent: ['adj.'],
  outermost: ['adj.'],
  tortuous: ['adj.'],
  vagrant: ['adj.', 'n.'],
  delirium: ['n.'],
  cipher: ['n.'],
  contributory: ['adj.'],
  diminution: ['n.'],
  verbalize: ['v.'],
  wanna: ['v.'],
  cohere: ['vi.'],
  cascara: ['n.'],
  dignify: ['vt.'],
  bluster: ['v.'],
  lethargy: ['n.'],
  centric: ['adj.'],
  inactivate: ['vt.'],
  plaudit: ['n.'],
  grump: ['v.', 'n.'],
  sprain: ['v.', 'n.'],
  adroit: ['adj.'],
  frivolity: ['n.'],
  grovel: ['vi.'],
  sneaker: ['n.'],
  demobilize: ['vt.'],
  'lost-and-found': ['n.'],
  diction: ['n.'],
  expropriate: ['vt.'],
  silversmith: ['n.'],
  granular: ['adj.'],
  indigestion: ['n.'],
  preliterate: ['adj.'],
  citadel: ['n.'],
  venturesome: ['adj.'],
  shirk: ['v.'],
  condole: ['vi.'],
  silica: ['n.'],
  dissimulate: ['v.'],
  respire: ['vi.'],
  systematize: ['vt.'],
  overcharge: ['v.', 'n.'],
  saucy: ['adj.'],
  unbridgeable: ['adj.'],
  graphics: ['n.'],
  larynx: ['n.'],
  amalgamation: ['n.'],
  waggle: ['v.'],
  mechanize: ['vt.'],
  matrimony: ['n.'],
  suffragist: ['n.'],
  melodious: ['adj.'],
  ethnology: ['n.'],
  terminus: ['n.'],
  synchronizer: ['n.'],
  dorsal: ['adj.'],
  troposphere: ['n.'],
  swindle: ['v.', 'n.'],
  imagist: ['n.', 'adj.'],
  expedient: ['adj.', 'n.'],
  ensconce: ['vt.'],
  antecede: ['vt.'],
  atrophy: ['n.', 'v.'],
  biannual: ['adj.'],
  scruple: ['n.'],
  quiescent: ['adj.'],
  seismology: ['n.'],
  multiplicative: ['adj.'],
  eviscerate: ['vt.'],
  famish: ['v.'],
  igneous: ['adj.'],
  rotational: ['adj.'],
  rustproof: ['adj.'],
  abridge: ['vt.'],
  nosy: ['adj.'],
  readability: ['n.'],
  rancorous: ['adj.'],
  chronical: ['adj.'],
  alkali: ['n.'],
  fortuitous: ['adj.'],
  deceitful: ['adj.'],
  sedimentary: ['adj.'],
  tedium: ['n.'],
  afoul: ['adv.'],
  middleman: ['n.'],
  lithosphere: ['n.'],
  saturn: ['n.'],
  lipid: ['n.'],
  outgas: ['vt.'],
  puritanical: ['adj.'],
  inanity: ['n.'],
  fumigate: ['vt.'],
  verbiage: ['n.'],
  cuneiform: ['adj.'],
  plumage: ['n.'],
  locomotion: ['n.'],
  swampy: ['adj.'],
  infirm: ['adj.'],
  annul: ['vt.'],
  mesolithic: ['adj.', 'n.'],
  grievous: ['adj.'],
  oblong: ['adj.', 'n.'],
  convex: ['adj.'],
  monogamy: ['n.'],
  torpor: ['n.'],
  semiotics: ['n.'],
  indecipherable: ['adj.'],
  bisect: ['vt.'],
  sewerage: ['n.'],
  chivalrous: ['adj.'],
  dateline: ['n.'],
  ware: ['n.'],
  weathering: ['n.'],
  stagecoach: ['n.'],
  injurious: ['adj.'],
  focalize: ['vt.'],
  toady: ['v.', 'n.'],
  ideomotor: ['adj.'],
  turnpike: ['n.'],
  outrageously: ['adv.'],
  ponderous: ['adj.'],
  sinuous: ['adj.'],
  fungi: ['n.'],
  proofread: ['v.'],
  numeric: ['adj.'],
  domicile: ['n.'],
  dissolute: ['adj.'],
  interrelate: ['v.'],
  entreat: ['v.'],
  smelting: ['n.'],
  hibernation: ['n.'],
  seashore: ['n.'],
  concave: ['adj.'],
  ornithology: ['n.'],
  perspicuous: ['adj.'],
  platitude: ['n.'],
  sledding: ['n.'],
  fahrenheit: ['adj.', 'n.'],
  congest: ['v.'],
  landmass: ['n.'],
  abbey: ['n.'],
  alienable: ['adj.'],
  unconsolidated: ['adj.'],
  foreshorten: ['vt.'],
  filial: ['adj.'],
  solder: ['v.', 'n.'],
  adventitious: ['adj.'],
  extort: ['vt.'],
  husbandry: ['n.'],
  elongate: ['v.'],
  subspecies: ['n.'],
  hieratic: ['adj.'],
  monotony: ['n.'],
  electrolysis: ['n.'],
  folkway: ['n.'],
  canvass: ['v.'],
  tectonics: ['n.'],
  spinet: ['n.'],
  spiny: ['adj.'],
  compressible: ['adj.'],
  'criss-cross': ['v.', 'n.', 'adj.'],
  methanol: ['n.'],
  pheromone: ['n.'],
  desegregate: ['v.'],
  girder: ['n.'],
  exponent: ['n.'],
  derivation: ['n.'],
  juridical: ['adj.'],
  curtsy: ['n.', 'vi.'],
  culpable: ['adj.'],
  backlighting: ['n.'],
  dexterous: ['adj.'],
  concord: ['n.'],
  ductile: ['adj.'],
  conciliate: ['v.'],
  vivify: ['vt.'],
  behaviorism: ['n.'],
  behaviourism: ['n.'],
  notate: ['vt.'],
  artesian: ['adj.'],
  mismanage: ['vt.'],
  watercourse: ['n.'],
  slough: ['v.', 'n.'],
  spun: ['adj.'],
  bicameral: ['adj.'],
  tremulous: ['adj.'],
  roe: ['n.'],
  doodle: ['v.', 'n.'],
  gentility: ['n.'],
  'wedge-shaped': ['adj.'],
  alga: ['n.'],
  hieroglyph: ['n.'],
  pharaoh: ['n.'],
  subjugate: ['vt.'],
  abbreviate: ['vt.'],
  crustal: ['adj.'],
  olfactory: ['adj.'],
  calculable: ['adj.'],
  shipwright: ['n.'],
  hydrothermal: ['adj.'],
  disquiet: ['n.', 'v.'],
  credentialism: ['n.'],
  neolithic: ['adj.', 'n.'],
  spellbind: ['vt.'],
  recessive: ['adj.'],
  constricted: ['adj.'],
  disrepute: ['n.'],
  operant: ['adj.', 'n.'],
  cellist: ['n.'],
  jupiter: ['n.'],
  eclecticism: ['n.'],
  ordinate: ['n.'],
  apprise: ['vt.'],
  plankton: ['n.'],
  deductive: ['adj.'],
  spheroid: ['n.'],
  cowhand: ['n.'],
  simile: ['n.'],
  combustible: ['adj.'],
  reapply: ['v.'],
  polygon: ['n.'],
  infatuate: ['vt.'],
  provincialism: ['n.'],
  auspicious: ['adj.'],
  lighthearted: ['adj.'],
  mercantile: ['adj.'],
  stratigraphy: ['n.'],
  angiosperm: ['n.'],
  uppermost: ['adj.', 'adv.'],
  expeditious: ['adj.'],
  calamitous: ['adj.'],
  consort: ['v.', 'n.'],
  vocalize: ['v.'],
  myopic: ['adj.'],
  illegible: ['adj.'],
  blues: ['n.'],
  defecate: ['vi.'],
  perishable: ['adj.'],
  hazel: ['n.', 'adj.'],
  tableland: ['n.'],
  aurora: ['n.'],
  complacence: ['n.'],
  empress: ['n.'],
  babylonian: ['adj.', 'n.'],
  nauseous: ['adj.'],
  // ---- coca2w 剩余特殊词 ----
  should: ['aux.'],
  let: ['v.'],
  "mm-hmm": ['int.'],
  "o''clock": ['adv.'],
  bosnian: ['adj.', 'n.'],
  taliban: ['n.'],
  freeman: ['n.'],
  furnishings: ['n.'],
  chile: ['n.'],
  'same-sex': ['adj.'],
  midwestern: ['adj.'],
  'medium-high': ['adj.'],
  'problem-solving': ['adj.', 'n.'],
  'self-efficacy': ['n.'],
  'all-american': ['adj.', 'n.'],
  'anti-war': ['adj.'],
  headnote: ['n.'],
  pentagon: ['n.'],
  rearview: ['adj.'],
  sidebar: ['n.'],
  'wake-up': ['n.', 'adj.'],
  aw: ['int.'],
  ipod: ['n.'],
  "y''all": ['pron.'],
  'second-largest': ['adj.'],
  appalachian: ['adj.', 'n.'],
  'prize-winning': ['adj.'],
  'multimillion-dollar': ['adj.'],
  anova: ['n.'],
  'credit-card': ['adj.'],
  'land-use': ['adj.'],
  'million-dollar': ['adj.'],
  residuals: ['n.'],
  'much-needed': ['adj.'],
  'regular-season': ['adj.'],
  creole: ['n.', 'adj.'],
  'take-out': ['n.', 'adj.'],
  payback: ['n.'],
  'self-reported': ['adj.'],
  'arab-israeli': ['adj.'],
  chives: ['n.'],
  'number-one': ['adj.'],
  'multi-ethnic': ['adj.'],
  'fiber-optic': ['adj.'],
  'at-bat': ['n.'],
  'post-traumatic': ['adj.'],
  'worst-case': ['adj.'],
  'small-business': ['adj.'],
  'non-native': ['adj.'],
  'civil-military': ['adj.'],
  bingo: ['int.', 'n.'],
  serotonin: ['n.'],
  'teacher-librarian': ['n.'],
  'mid-afternoon': ['n.', 'adj.'],
  'english-language': ['adj.'],
  audubon: ['n.'],
  'stainless-steel': ['adj.'],
  'pre-dawn': ['adj.'],
  'mid-morning': ['n.', 'adj.'],
  'he/she': ['pron.'],
  'co-director': ['n.'],
  'private-sector': ['adj.'],
  'israeli-palestinian': ['adj.'],
  nightstand: ['n.'],
  't-test': ['n.'],
  'co-write': ['v.'],
  coursework: ['n.'],
  'semi-automatic': ['adj.'],
  'at-large': ['adj.'],
  'mexican-american': ['adj.', 'n.'],
  'student-athlete': ['n.'],
  'co-chair': ['n.'],
  'single-parent': ['adj.'],
  mri: ['n.'],
  'first-person': ['adj.', 'n.'],
  grandkid: ['n.'],
  'self-report': ['n.', 'v.'],
  'spanish-speaking': ['adj.'],
  'fourth-quarter': ['adj.'],
  'old-growth': ['adj.'],
  umm: ['int.'],
  'co-host': ['n.'],
  khakis: ['n.'],
  'test-retest': ['n.'],
  airstrike: ['n.'],
  'extra-virgin': ['adj.'],
  ballgame: ['n.'],
  'medium-low': ['adj.'],
  'likert-type': ['adj.'],
  'school-age': ['adj.'],
  'parent-child': ['adj.'],
  sandinista: ['n.'],
  'third-largest': ['adj.'],
  'child-rearing': ['n.'],
  'co-found': ['v.'],
  ahh: ['int.'],
  'spanish-language': ['adj.'],
  alamo: ['n.'],
  floodwaters: ['n.'],
  'long-term-care': ['adj.'],
  'case-by-case': ['adj.'],
  coffeehouse: ['n.'],
  'old-school': ['adj.'],
  'video-game': ['adj.'],
  'self-perception': ['n.'],
  'first-quarter': ['adj.'],
  'chain-link': ['adj.'],
  'early-morning': ['adj.'],
  'euro-american': ['adj.'],
  'meta-analysis': ['n.'],
  'gamma-ray': ['adj.'],
  'co-sponsor': ['n.', 'v.'],
  cutthroat: ['adj.', 'n.'],
  'above-average': ['adj.'],
  'anti-drug': ['adj.'],
  'inter-american': ['adj.'],
  lightbulb: ['n.'],
  'long-held': ['adj.'],
  'free-trade': ['adj.'],
  'public-relations': ['adj.'],
  'mental-health': ['adj.'],
  'minor-league': ['adj.'],
  'deep-water': ['adj.'],
  'first-place': ['adj.'],
  'science-fiction': ['adj.'],
};

/** 末尾词性标记（英文括号/中文括号）："预先确定，注定 (vt.)" → vt. */
const TRAILING_POS_RE = /(?:\(|（)\s*(n|v|vt|vi|adj|adv|prep|conj|art|pron|num|int|aux|abbr|det|modal|pl|sing)\.?\s*(?:\)|）)\s*$/;

export const POS_FULL = {
  n: 'n.', v: 'v.', vt: 'vt.', vi: 'vi.', adj: 'adj.', adv: 'adv.', prep: 'prep.',
  conj: 'conj.', art: 'art.', pron: 'pron.', num: 'num.', int: 'int.', aux: 'aux.',
  abbr: 'abbr.', det: 'det.', modal: 'modal.', pl: 'pl.', sing: 'sing.',
};

/** 从释义末尾提取词性标记，返回 { pos, text } 或 null */
export function extractTrailingPos(meaning) {
  const s = String(meaning).trim();
  const m = s.match(TRAILING_POS_RE);
  if (!m) return null;
  const key = m[1].toLowerCase();
  const pos = POS_FULL[key];
  if (!pos) return null;
  return { pos, text: s.slice(0, m.index).replace(/[\s,，、;；]+$/, '').trim() };
}

/** 后缀规则推断：返回词性数组或 null */
const ADJ_ENDINGS = [
  'able', 'ible', 'ous', 'ful', 'less', 'ic', 'ical', 'al', 'ive', 'ed', 'ing',
  'y', 'ish', 'esque', 'like', 'some', 'proof', 'free', 'worthy', 'ward', 'fold',
];
const NOUN_ENDINGS = [
  'tion', 'sion', 'ness', 'ity', 'ment', 'ism', 'logy', 'ology', 'ics', 'ist',
  'er', 'or', 'ance', 'ence', 'ancy', 'ency', 'age', 'ure', 'cy', 'ry', 'ship',
  'hood', 'dom', 'graphy', 'metry', 'tude', 'ty', 'eer', 'arian', 'arium',
];
const VERB_ENDINGS = ['ize', 'ise', 'ify', 'en'];
const ADV_ENDINGS = ['ly'];
/** -ly 结尾但其实是形容词的常见词 */
const LY_ADJ = new Set([
  'friendly', 'costly', 'lovely', 'lonely', 'ugly', 'elderly', 'silly', 'lively',
  'deadly', 'likely', 'unlikely', 'early', 'orderly', 'manly', 'womanly', 'fatherly',
  'motherly', 'brotherly', 'sisterly', 'ghostly', 'homely', 'comely', 'unruly',
]);

/** 复合词（含连字符）→ 形容词的常见词尾成分 */
const COMPOUND_ADJ_TAILS = [
  'year', 'year-old', 'day', 'month', 'week', 'hour', 'minute', 'century', 'decade',
  'based', 'related', 'free', 'long', 'wide', 'size', 'story', 'party', 'room',
  'bedroom', 'lane', 'grade', 'family', 'service', 'resolution', 'market', 'end',
  'income', 'wage', 'speed', 'energy', 'performance', 'quality', 'resolution',
  'old', 'time', 'round', 'term', 'part', 'way', 'generation', 'floor', 'level',
  'stage', 'budget', 'profile', 'pressure', 'tech', 'tech', 'white', 'black',
  'blue', 'green', 'red', 'wing', 'wheel', 'hand', 'foot', 'wire', 'wired',
  'glass', 'screen', 'fly', 'driven', 'powered', 'operated', 'owned', 'led',
  'sponsored', 'funded', 'run', 'made', 'built', 'designed', 'generated',
  'documented', 'developed', 'tested', 'managed', 'trained', 'educated',
  'armed', 'haired', 'eyed', 'faced', 'seater', 'lane', 'door', 'way', 'sided',
];

/** 数字词：one-third / twenty-five / thirty-two 等 */
const NUMBER_WORD_RE = /^(zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|million|billion)([- ](zero|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred|thousand|million|billion|first|second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth|half|quarter|third))*$/;

function isNumberWord(w) {
  return NUMBER_WORD_RE.test(w);
}

/** 推断单个单词（小写）的词性数组 */
export function inferPosBySuffix(word) {
  const w = String(word).toLowerCase().trim();
  if (!w) return null;

  // 手动映射表优先
  if (POS_OVERRIDES[w]) return POS_OVERRIDES[w];

  // 数词：one-third / twenty-five / one half
  if (isNumberWord(w)) return ['num.'];

  // 复合词（含连字符）
  if (w.includes('-')) {
    // 数字+名词复合：five-year / 3-day → adj.；但 one-third / twenty-five 已在上面处理
    const parts = w.split('-');
    const headNum = /^(one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety|hundred)$/.test(parts[0] || '');
    if (headNum && parts.length >= 2) return ['adj.'];
    const tail = parts[parts.length - 1] || '';
    for (const t of COMPOUND_ADJ_TAILS) {
      if (tail.endsWith(t) || tail === t) return ['adj.'];
    }
    // 常见名词性复合词
    if (/^(editor|son|daughter|brother|sister|father|mother|grand|step|half|great|father|mother)-/.test(w)) return ['n.'];
    if (/(chief|in-law|of-war|of-state)$/.test(w)) return ['n.'];
    return null;
  }

  // 形容词后缀（先于名词，避免 -al 之类误判——但 -al 大多形容词）
  for (const e of ADJ_ENDINGS) {
    if (w.endsWith(e)) {
      // -ed/-ing 分词也可能是动词，但释义场景多为形容词
      if ((e === 'ed' || e === 'ing') && w.length <= 4) break;
      return ['adj.'];
    }
  }

  // 副词 -ly（排除常见形容词）
  for (const e of ADV_ENDINGS) {
    if (w.endsWith(e)) {
      if (LY_ADJ.has(w)) return ['adj.'];
      return ['adv.'];
    }
  }

  // 名词后缀
  for (const e of NOUN_ENDINGS) {
    if (w.endsWith(e)) return ['n.'];
  }

  // 动词后缀
  for (const e of VERB_ENDINGS) {
    if (w.endsWith(e)) return ['v.'];
  }

  return null;
}

/** 给释义分段按词性数组加前缀：m 与 posList 按顺序对齐 */
export function applyPosList(entry, posList) {
  if (!posList || posList.length === 0) return;
  const m = entry.m;
  const posStr = [...new Set(posList)].join('；');
  if (m.length <= 1) {
    entry.pos = posStr;
    entry.m = [posList[0] + (m[0] || '')];
  } else if (m.length === posList.length) {
    entry.pos = posStr;
    entry.m = m.map((x, i) => posList[i] + x);
  } else {
    entry.pos = posStr;
    entry.m = m.map((x, i) => (posList[i % posList.length] ?? posList[0]) + x);
  }
}

/** 顶层修复入口：返回是否已修复 */
export function fixEntry(entry) {
  if (!entry || !Array.isArray(entry.m) || entry.m.length === 0) return false;
  const hasPrefix = entry.m.every((x) => /^[a-zA-Z]+\./.test(String(x).trim()));
  if (hasPrefix && entry.pos) return false;

  const word = String(entry.w || '').toLowerCase().trim();

  // 1. 尾部词性标记提取（逐段）
  let changed = false;
  const newM = entry.m.map((seg) => {
    const t = extractTrailingPos(seg);
    if (t) {
      changed = true;
      return t.pos + t.text;
    }
    return seg;
  });
  if (changed) {
    entry.m = newM;
    // 提取后的 pos 汇总
    const posSet = new Set();
    entry.m.forEach((seg) => {
      const mm = seg.match(/^([a-zA-Z]+)\./);
      if (mm) posSet.add(POS_FULL[mm[1].toLowerCase()] || mm[0]);
    });
    if (posSet.size) entry.pos = [...posSet].join('；');
    return true;
  }

  // 2. 手动映射表 / 后缀规则
  const posList = inferPosBySuffix(word);
  if (posList) {
    applyPosList(entry, posList);
    return true;
  }

  return false;
}
